"""
Prompt loader for article content generation.

Safe messaging guidelines incorporated:
- AFSP (American Foundation for Suicide Prevention) safe messaging guidelines
- SAMHSA recommendations for mental health communication
- Non-stigmatising, person-first language
- Hope-oriented framing with professional support pathways
- No sensationalism, no detailed descriptions of harmful methods

Edit prompts/article_system.txt to update the system prompt.
"""

from pathlib import Path

_PROMPTS_DIR = Path(__file__).parent / "prompts"

SYSTEM_PROMPT: str = (_PROMPTS_DIR / "article_system.txt").read_text(encoding="utf-8")

DISCLAIMER = (
    "_This article was generated by Claude (Anthropic) and has been reviewed "
    "by a mental health professional before publication. It is intended for "
    "educational purposes only and is not a substitute for professional mental "
    "health advice, diagnosis, or treatment._"
)


def build_user_prompt(topic: str) -> str:
    return (
        f"Write a mental health article about the following topic: {topic}\n\n"
        "Follow all safe messaging and formatting guidelines in your instructions."
    )
