"""
Prompt loader for article content generation.

Safe messaging guidelines incorporated:
- AFSP (American Foundation for Suicide Prevention) safe messaging guidelines
- SAMHSA recommendations for mental health communication
- Non-stigmatising, person-first language
- Hope-oriented framing with professional support pathways
- No sensationalism, no detailed descriptions of harmful methods

Edit prompts/article_system.txt to update the system prompt.
"""

from pathlib import Path

_PROMPTS_DIR = Path(__file__).parent / "prompts"

SYSTEM_PROMPT: str = (_PROMPTS_DIR / "article_system.txt").read_text(encoding="utf-8")

DISCLAIMER = (
    "_This article was generated by Claude (Anthropic) and has not yet been "
    "reviewed by a human expert. It is intended for educational purposes only "
    "and is not a substitute for professional mental health advice, diagnosis, "
    "or treatment._"
)


def build_user_prompt(topic: str) -> str:
    return (
        f"Write a mental health article about the following topic: {topic}\n\n"
        "Follow all safe messaging and formatting guidelines in your instructions."
    )


def parse_body_and_tags(raw: str) -> tuple[str, list[str]]:
    """Split Claude's response into (body, tags).

    Expects the last line to be `TAGS: tag1, tag2` (or `TAGS:` for none).
    If no TAGS line is found, returns the full text as body with no tags.
    """
    lines = raw.strip().splitlines()
    if lines and lines[-1].upper().startswith("TAGS:"):
        tag_line = lines[-1][len("TAGS:"):].strip()
        tags = [t.strip() for t in tag_line.split(",") if t.strip()]
        body = "\n".join(lines[:-1]).strip()
        return body, tags
    return raw.strip(), []
